services:
  ziggy:
    build: .
    container_name: ziggy
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=default
      - LOG_HANDLERS=console
      - LOG_FILE=logs/app.log
      - LOG_MAX_BYTES=10485760
      - LOG_BACKUP_COUNT=5
      - ACCESS_LOG=true
      # Gunicorn Configuration
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-30}
      - GUNICORN_LOG_LEVEL=${GUNICORN_LOG_LEVEL:-info}
      - GUNICORN_ACCESS_LOG=${GUNICORN_ACCESS_LOG:--}
      - GUNICORN_MAX_REQUESTS=${GUNICORN_MAX_REQUESTS:-1000}
      - GUNICORN_MAX_REQUESTS_JITTER=${GUNICORN_MAX_REQUESTS_JITTER:-50}
      # MQTT Configuration
      - MQTT_ENABLED=true
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - ZIGBEE2MQTT_BRIDGE_NAME=${ZIGBEE2MQTT_BRIDGE_NAME:-mybridge}
      - ZIGBEE2MQTT_BASE_TOPIC=${ZIGBEE2MQTT_BASE_TOPIC:-zigbee2mqtt}
      - MQTT_CLIENT_ID=ziggy
    # Uncomment to persist logs
    # volumes:
    #   - ./logs:/app/logs
    restart: unless-stopped
