services:
  ziggy:
    build: .
    container_name: ziggy
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - LOG_FORMAT=default
      - LOG_HANDLERS=console
      - LOG_FILE=logs/app.log
      - LOG_MAX_BYTES=10485760
      - LOG_BACKUP_COUNT=5
    # Uncomment to persist logs
    # volumes:
    #   - ./logs:/app/logs
    restart: unless-stopped
