{
 "title": "Ziggy Zigbee2MQTT",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bridge_name",
    "label": "Bridge",
    "query": {
     "query": "label_values(ziggy_zigbee2mqtt_device_messages,bridge_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Zigbee2MQTT Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bridge State Online",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "repeat": "bridge_name",
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(bridge_name) (ziggy_zigbee2mqtt_bridge_state{bridge_name=~\"$bridge_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridge Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "bridge_name",
   "targets": [
    {
     "expr": "max by(bridge_name, log_level, permit_join, restart_required) (ziggy_zigbee2mqtt_bridge_info_bridge_info{bridge_name=~\"$bridge_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zigbee2MQTT Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bridge Coordinator Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "repeat": "bridge_name",
     "targets": [
      {
       "expr": "max by(bridge_name, ieee_address, type) (ziggy_zigbee2mqtt_bridge_info_coordinator_info{bridge_name=~\"$bridge_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bridge Version Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "repeat": "bridge_name",
     "targets": [
      {
       "expr": "max by(bridge_name, commit, version) (ziggy_zigbee2mqtt_bridge_info_version_info{bridge_name=~\"$bridge_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Device Basics Zigbee2MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Device msgs/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "ziggy_zigbee2mqtt_device_messages_per_sec{bridge_name=~\"$bridge_name\"}",
     "legendFormat": "{{bridge_name}} - {{device_ieee}}"
    }
   ]
  },
  {
   "title": "Device Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "ziggy_zigbee2mqtt_device_messages{bridge_name=~\"$bridge_name\"}",
     "legendFormat": "{{bridge_name}} - {{device_ieee}}"
    }
   ]
  },
  {
   "title": "Device Network Address Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "ziggy_zigbee2mqtt_device_network_address_changes{bridge_name=~\"$bridge_name\"} > 0",
     "legendFormat": "{{bridge_name}} - {{device_ieee}}"
    }
   ]
  },
  {
   "title": "Device Leave Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "ziggy_zigbee2mqtt_device_leave_count{bridge_name=~\"$bridge_name\"} > 0",
     "legendFormat": "{{bridge_name}} - {{device_ieee}}"
    }
   ]
  },
  {
   "title": "Devices Detailed Zigbee2MQTT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Appearances Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(ziggy_zigbee2mqtt_device_appearances_total{bridge_name=~\"$bridge_name\"}[$__rate_interval])",
       "legendFormat": "{{bridge_name}} - {{device_ieee}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "App Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "repeat": "bridge_name",
     "targets": [
      {
       "expr": "max by(bridge_name, app_name, environment_environment, environment_log_level, platform_machine, platform_release, platform_system, platform_version, python_version, python_implementation, version) (ziggy_app_info_info{bridge_name=~\"$bridge_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}